version: '3.0'

services:
  database-spa:
    container_name: database-spa
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: spadb
      MYSQL_USER: spauser
      MYSQL_PASSWORD: spapass
    ports:
      - '4306:3306'
    volumes:
      - .docker/mysql:/var/lib/mysql

  
  php-spa:
    container_name: php-spa
    build:
      context: .docker/php
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/spa
    depends_on:
      - database-spa



  nginx-spa:
    container_name: nginx-spa
    image: nginx:stable-alpine
    ports:
      - '8060:80'
    volumes:
      - .:/var/www/spa
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-spa
      - database-spa
 
  phpmyadmin-spa:
    image: phpmyadmin
    restart: always
    ports:
      - 10000:80
    environment:
      PMA_HOST: database-spa